Parser - call command
Cavonstavant/mes_equipes pull request #49
Opened 2022-05-10 15:20 UTC by osvegn

Pull request link to this issue: #31 .

2022-05-11 15:23 UTC, LucasTesnier requested changes
NTR!

2022-05-11 15:23 UTC, LucasTesnier commented on server/src/parser/call_command.c
> +    for (int i = 0; i < 14; i++) {
Add a macro for Command_Tab size

2022-05-11 15:23 UTC, LucasTesnier commented on server/src/parser/cli_commands.c
> +static const cli_command_t commands[14] = {
Add a macro for Command_Tab size

2022-05-11 15:36 UTC, Cavonstavant commented on server/src/parser/cli_commands.c
> +}
Consider adding a function to retrieve one command info by giving it's name as a parameter

2022-05-12 07:45 UTC, Cavonstavant approved these changes
LGTM

2022-05-12 08:04 UTC, LucasTesnier approved these changes
NTR!

2022-05-12 09:22 UTC, merged